/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface BookmarkResponse
 */
export interface BookmarkResponse {
    /**
     * 
     * @type {string}
     * @memberof BookmarkResponse
     */
    'id'?: string;
    /**
     * 
     * @type {number}
     * @memberof BookmarkResponse
     */
    'userId'?: number;
    /**
     * 
     * @type {number}
     * @memberof BookmarkResponse
     */
    'bookId'?: number;
    /**
     * 
     * @type {number}
     * @memberof BookmarkResponse
     */
    'chapterNumber'?: number;
    /**
     * 
     * @type {string}
     * @memberof BookmarkResponse
     */
    'createdAt'?: string;
}

