/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CrawlResponse } from '../models';
// @ts-ignore
import type { Metadata } from '../models';
/**
 * CrawlControllerApi - axios parameter creator
 * @export
 */
export const CrawlControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {Metadata} metadata 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        crawl: async (metadata: Metadata, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'metadata' is not null or undefined
            assertParamExists('crawl', 'metadata', metadata)
            const localVarPath = `/crawl/crawl`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(metadata, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * CrawlControllerApi - functional programming interface
 * @export
 */
export const CrawlControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = CrawlControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {Metadata} metadata 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async crawl(metadata: Metadata, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CrawlResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.crawl(metadata, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CrawlControllerApi.crawl']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * CrawlControllerApi - factory interface
 * @export
 */
export const CrawlControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = CrawlControllerApiFp(configuration)
    return {
        /**
         * 
         * @param {CrawlControllerApiCrawlRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        crawl(requestParameters: CrawlControllerApiCrawlRequest, options?: RawAxiosRequestConfig): AxiosPromise<CrawlResponse> {
            return localVarFp.crawl(requestParameters.metadata, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for crawl operation in CrawlControllerApi.
 * @export
 * @interface CrawlControllerApiCrawlRequest
 */
export interface CrawlControllerApiCrawlRequest {
    /**
     * 
     * @type {Metadata}
     * @memberof CrawlControllerApiCrawl
     */
    readonly metadata: Metadata
}

/**
 * CrawlControllerApi - object-oriented interface
 * @export
 * @class CrawlControllerApi
 * @extends {BaseAPI}
 */
export class CrawlControllerApi extends BaseAPI {
    /**
     * 
     * @param {CrawlControllerApiCrawlRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CrawlControllerApi
     */
    public crawl(requestParameters: CrawlControllerApiCrawlRequest, options?: RawAxiosRequestConfig) {
        return CrawlControllerApiFp(this.configuration).crawl(requestParameters.metadata, options).then((request) => request(this.axios, this.basePath));
    }
}

