/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface BookAddResponse
 */
export interface BookAddResponse {
    /**
     * 
     * @type {string}
     * @memberof BookAddResponse
     */
    'username'?: string;
    /**
     * 
     * @type {string}
     * @memberof BookAddResponse
     */
    'bookId'?: string;
    /**
     * 
     * @type {string}
     * @memberof BookAddResponse
     */
    'addDate'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof BookAddResponse
     */
    'addSuccess'?: boolean;
}

