/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface BookIndexResponse
 */
export interface BookIndexResponse {
    /**
     * 
     * @type {string}
     * @memberof BookIndexResponse
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof BookIndexResponse
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof BookIndexResponse
     */
    'subtitle'?: string;
    /**
     * 
     * @type {string}
     * @memberof BookIndexResponse
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof BookIndexResponse
     */
    'author'?: string;
    /**
     * 
     * @type {string}
     * @memberof BookIndexResponse
     */
    'coverUrl'?: string;
    /**
     * 
     * @type {number}
     * @memberof BookIndexResponse
     */
    'chapterCount'?: number;
    /**
     * 
     * @type {string}
     * @memberof BookIndexResponse
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof BookIndexResponse
     */
    'updatedAt'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof BookIndexResponse
     */
    'categories'?: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof BookIndexResponse
     */
    'completed'?: boolean;
}

