/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ApiResponseLong
 */
export interface ApiResponseLong {
    /**
     * 
     * @type {number}
     * @memberof ApiResponseLong
     */
    'data'?: number;
    /**
     * 
     * @type {string}
     * @memberof ApiResponseLong
     */
    'message'?: string;
    /**
     * 
     * @type {number}
     * @memberof ApiResponseLong
     */
    'code'?: number;
}

