/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ChapterResponse } from './chapter-response';

/**
 * 
 * @export
 * @interface ApiResponseListChapterResponse
 */
export interface ApiResponseListChapterResponse {
    /**
     * 
     * @type {Array<ChapterResponse>}
     * @memberof ApiResponseListChapterResponse
     */
    'data'?: Array<ChapterResponse>;
    /**
     * 
     * @type {string}
     * @memberof ApiResponseListChapterResponse
     */
    'message'?: string;
    /**
     * 
     * @type {number}
     * @memberof ApiResponseListChapterResponse
     */
    'code'?: number;
}

