/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ChapterRequest
 */
export interface ChapterRequest {
    /**
     * 
     * @type {string}
     * @memberof ChapterRequest
     */
    'bookId'?: string;
    /**
     * 
     * @type {string}
     * @memberof ChapterRequest
     */
    'title'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ChapterRequest
     */
    'images'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof ChapterRequest
     */
    'content'?: string;
    /**
     * 
     * @type {number}
     * @memberof ChapterRequest
     */
    'chapterNumber'?: number;
}

