/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { FromUrlUploadResponse } from './from-url-upload-response';

/**
 * 
 * @export
 * @interface ApiResponseFromUrlUploadResponse
 */
export interface ApiResponseFromUrlUploadResponse {
    /**
     * 
     * @type {FromUrlUploadResponse}
     * @memberof ApiResponseFromUrlUploadResponse
     */
    'data'?: FromUrlUploadResponse;
    /**
     * 
     * @type {string}
     * @memberof ApiResponseFromUrlUploadResponse
     */
    'message'?: string;
    /**
     * 
     * @type {number}
     * @memberof ApiResponseFromUrlUploadResponse
     */
    'code'?: number;
}

