/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UploadResponse
 */
export interface UploadResponse {
    /**
     * 
     * @type {string}
     * @memberof UploadResponse
     */
    'url'?: string;
    /**
     * 
     * @type {string}
     * @memberof UploadResponse
     */
    'publicId'?: string;
    /**
     * 
     * @type {string}
     * @memberof UploadResponse
     */
    'category'?: string;
    /**
     * 
     * @type {string}
     * @memberof UploadResponse
     */
    'uploadedAt'?: string;
}

