/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface BookInfo
 */
export interface BookInfo {
    /**
     * 
     * @type {string}
     * @memberof BookInfo
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof BookInfo
     */
    'author'?: string;
    /**
     * 
     * @type {string}
     * @memberof BookInfo
     */
    'description'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof BookInfo
     */
    'categories'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof BookInfo
     */
    'coverUrl'?: string;
}

