/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ApiResponseChapterResponse } from '../models';
// @ts-ignore
import type { ApiResponseListChapterResponse } from '../models';
// @ts-ignore
import type { ApiResponseLong } from '../models';
/**
 * ExternalChapterAPIsApi - axios parameter creator
 * @export
 */
export const ExternalChapterAPIsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Count the number of chapters in a book
         * @summary Count chapters
         * @param {string} bookId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        countChaptersByBookId: async (bookId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'bookId' is not null or undefined
            assertParamExists('countChaptersByBookId', 'bookId', bookId)
            const localVarPath = `/chapter/chapters/book/{bookId}/count`
                .replace(`{${"bookId"}}`, encodeURIComponent(String(bookId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Fetch a chapter of a book by its number
         * @summary Get chapter by number
         * @param {string} bookId 
         * @param {number} chapterNumber 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getChapterByBookIdAndNumber: async (bookId: string, chapterNumber: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'bookId' is not null or undefined
            assertParamExists('getChapterByBookIdAndNumber', 'bookId', bookId)
            // verify required parameter 'chapterNumber' is not null or undefined
            assertParamExists('getChapterByBookIdAndNumber', 'chapterNumber', chapterNumber)
            const localVarPath = `/chapter/chapters/book/{bookId}/number/{chapterNumber}`
                .replace(`{${"bookId"}}`, encodeURIComponent(String(bookId)))
                .replace(`{${"chapterNumber"}}`, encodeURIComponent(String(chapterNumber)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Fetch a chapter by chapterId and bookId
         * @summary Get chapter by ID
         * @param {string} bookId 
         * @param {string} chapterId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getChapterById: async (bookId: string, chapterId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'bookId' is not null or undefined
            assertParamExists('getChapterById', 'bookId', bookId)
            // verify required parameter 'chapterId' is not null or undefined
            assertParamExists('getChapterById', 'chapterId', chapterId)
            const localVarPath = `/chapter/chapters/{bookId}/{chapterId}`
                .replace(`{${"bookId"}}`, encodeURIComponent(String(bookId)))
                .replace(`{${"chapterId"}}`, encodeURIComponent(String(chapterId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Fetch all chapters by bookId
         * @summary Get all chapters of a book
         * @param {string} bookId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getChaptersByBookId: async (bookId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'bookId' is not null or undefined
            assertParamExists('getChaptersByBookId', 'bookId', bookId)
            const localVarPath = `/chapter/chapters/book/{bookId}`
                .replace(`{${"bookId"}}`, encodeURIComponent(String(bookId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Fetch the last (latest) chapter of a book
         * @summary Get last chapter
         * @param {string} bookId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getLastChapterByBookId: async (bookId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'bookId' is not null or undefined
            assertParamExists('getLastChapterByBookId', 'bookId', bookId)
            const localVarPath = `/chapter/chapters/book/{bookId}/last`
                .replace(`{${"bookId"}}`, encodeURIComponent(String(bookId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ExternalChapterAPIsApi - functional programming interface
 * @export
 */
export const ExternalChapterAPIsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ExternalChapterAPIsApiAxiosParamCreator(configuration)
    return {
        /**
         * Count the number of chapters in a book
         * @summary Count chapters
         * @param {string} bookId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async countChaptersByBookId(bookId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseLong>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.countChaptersByBookId(bookId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ExternalChapterAPIsApi.countChaptersByBookId']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Fetch a chapter of a book by its number
         * @summary Get chapter by number
         * @param {string} bookId 
         * @param {number} chapterNumber 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getChapterByBookIdAndNumber(bookId: string, chapterNumber: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseChapterResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getChapterByBookIdAndNumber(bookId, chapterNumber, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ExternalChapterAPIsApi.getChapterByBookIdAndNumber']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Fetch a chapter by chapterId and bookId
         * @summary Get chapter by ID
         * @param {string} bookId 
         * @param {string} chapterId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getChapterById(bookId: string, chapterId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseChapterResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getChapterById(bookId, chapterId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ExternalChapterAPIsApi.getChapterById']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Fetch all chapters by bookId
         * @summary Get all chapters of a book
         * @param {string} bookId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getChaptersByBookId(bookId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseListChapterResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getChaptersByBookId(bookId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ExternalChapterAPIsApi.getChaptersByBookId']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Fetch the last (latest) chapter of a book
         * @summary Get last chapter
         * @param {string} bookId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getLastChapterByBookId(bookId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseChapterResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getLastChapterByBookId(bookId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ExternalChapterAPIsApi.getLastChapterByBookId']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ExternalChapterAPIsApi - factory interface
 * @export
 */
export const ExternalChapterAPIsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ExternalChapterAPIsApiFp(configuration)
    return {
        /**
         * Count the number of chapters in a book
         * @summary Count chapters
         * @param {ExternalChapterAPIsApiCountChaptersByBookIdRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        countChaptersByBookId(requestParameters: ExternalChapterAPIsApiCountChaptersByBookIdRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseLong> {
            return localVarFp.countChaptersByBookId(requestParameters.bookId, options).then((request) => request(axios, basePath));
        },
        /**
         * Fetch a chapter of a book by its number
         * @summary Get chapter by number
         * @param {ExternalChapterAPIsApiGetChapterByBookIdAndNumberRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getChapterByBookIdAndNumber(requestParameters: ExternalChapterAPIsApiGetChapterByBookIdAndNumberRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseChapterResponse> {
            return localVarFp.getChapterByBookIdAndNumber(requestParameters.bookId, requestParameters.chapterNumber, options).then((request) => request(axios, basePath));
        },
        /**
         * Fetch a chapter by chapterId and bookId
         * @summary Get chapter by ID
         * @param {ExternalChapterAPIsApiGetChapterByIdRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getChapterById(requestParameters: ExternalChapterAPIsApiGetChapterByIdRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseChapterResponse> {
            return localVarFp.getChapterById(requestParameters.bookId, requestParameters.chapterId, options).then((request) => request(axios, basePath));
        },
        /**
         * Fetch all chapters by bookId
         * @summary Get all chapters of a book
         * @param {ExternalChapterAPIsApiGetChaptersByBookIdRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getChaptersByBookId(requestParameters: ExternalChapterAPIsApiGetChaptersByBookIdRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseListChapterResponse> {
            return localVarFp.getChaptersByBookId(requestParameters.bookId, options).then((request) => request(axios, basePath));
        },
        /**
         * Fetch the last (latest) chapter of a book
         * @summary Get last chapter
         * @param {ExternalChapterAPIsApiGetLastChapterByBookIdRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getLastChapterByBookId(requestParameters: ExternalChapterAPIsApiGetLastChapterByBookIdRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseChapterResponse> {
            return localVarFp.getLastChapterByBookId(requestParameters.bookId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for countChaptersByBookId operation in ExternalChapterAPIsApi.
 * @export
 * @interface ExternalChapterAPIsApiCountChaptersByBookIdRequest
 */
export interface ExternalChapterAPIsApiCountChaptersByBookIdRequest {
    /**
     * 
     * @type {string}
     * @memberof ExternalChapterAPIsApiCountChaptersByBookId
     */
    readonly bookId: string
}

/**
 * Request parameters for getChapterByBookIdAndNumber operation in ExternalChapterAPIsApi.
 * @export
 * @interface ExternalChapterAPIsApiGetChapterByBookIdAndNumberRequest
 */
export interface ExternalChapterAPIsApiGetChapterByBookIdAndNumberRequest {
    /**
     * 
     * @type {string}
     * @memberof ExternalChapterAPIsApiGetChapterByBookIdAndNumber
     */
    readonly bookId: string

    /**
     * 
     * @type {number}
     * @memberof ExternalChapterAPIsApiGetChapterByBookIdAndNumber
     */
    readonly chapterNumber: number
}

/**
 * Request parameters for getChapterById operation in ExternalChapterAPIsApi.
 * @export
 * @interface ExternalChapterAPIsApiGetChapterByIdRequest
 */
export interface ExternalChapterAPIsApiGetChapterByIdRequest {
    /**
     * 
     * @type {string}
     * @memberof ExternalChapterAPIsApiGetChapterById
     */
    readonly bookId: string

    /**
     * 
     * @type {string}
     * @memberof ExternalChapterAPIsApiGetChapterById
     */
    readonly chapterId: string
}

/**
 * Request parameters for getChaptersByBookId operation in ExternalChapterAPIsApi.
 * @export
 * @interface ExternalChapterAPIsApiGetChaptersByBookIdRequest
 */
export interface ExternalChapterAPIsApiGetChaptersByBookIdRequest {
    /**
     * 
     * @type {string}
     * @memberof ExternalChapterAPIsApiGetChaptersByBookId
     */
    readonly bookId: string
}

/**
 * Request parameters for getLastChapterByBookId operation in ExternalChapterAPIsApi.
 * @export
 * @interface ExternalChapterAPIsApiGetLastChapterByBookIdRequest
 */
export interface ExternalChapterAPIsApiGetLastChapterByBookIdRequest {
    /**
     * 
     * @type {string}
     * @memberof ExternalChapterAPIsApiGetLastChapterByBookId
     */
    readonly bookId: string
}

/**
 * ExternalChapterAPIsApi - object-oriented interface
 * @export
 * @class ExternalChapterAPIsApi
 * @extends {BaseAPI}
 */
export class ExternalChapterAPIsApi extends BaseAPI {
    /**
     * Count the number of chapters in a book
     * @summary Count chapters
     * @param {ExternalChapterAPIsApiCountChaptersByBookIdRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ExternalChapterAPIsApi
     */
    public countChaptersByBookId(requestParameters: ExternalChapterAPIsApiCountChaptersByBookIdRequest, options?: RawAxiosRequestConfig) {
        return ExternalChapterAPIsApiFp(this.configuration).countChaptersByBookId(requestParameters.bookId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Fetch a chapter of a book by its number
     * @summary Get chapter by number
     * @param {ExternalChapterAPIsApiGetChapterByBookIdAndNumberRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ExternalChapterAPIsApi
     */
    public getChapterByBookIdAndNumber(requestParameters: ExternalChapterAPIsApiGetChapterByBookIdAndNumberRequest, options?: RawAxiosRequestConfig) {
        return ExternalChapterAPIsApiFp(this.configuration).getChapterByBookIdAndNumber(requestParameters.bookId, requestParameters.chapterNumber, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Fetch a chapter by chapterId and bookId
     * @summary Get chapter by ID
     * @param {ExternalChapterAPIsApiGetChapterByIdRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ExternalChapterAPIsApi
     */
    public getChapterById(requestParameters: ExternalChapterAPIsApiGetChapterByIdRequest, options?: RawAxiosRequestConfig) {
        return ExternalChapterAPIsApiFp(this.configuration).getChapterById(requestParameters.bookId, requestParameters.chapterId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Fetch all chapters by bookId
     * @summary Get all chapters of a book
     * @param {ExternalChapterAPIsApiGetChaptersByBookIdRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ExternalChapterAPIsApi
     */
    public getChaptersByBookId(requestParameters: ExternalChapterAPIsApiGetChaptersByBookIdRequest, options?: RawAxiosRequestConfig) {
        return ExternalChapterAPIsApiFp(this.configuration).getChaptersByBookId(requestParameters.bookId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Fetch the last (latest) chapter of a book
     * @summary Get last chapter
     * @param {ExternalChapterAPIsApiGetLastChapterByBookIdRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ExternalChapterAPIsApi
     */
    public getLastChapterByBookId(requestParameters: ExternalChapterAPIsApiGetLastChapterByBookIdRequest, options?: RawAxiosRequestConfig) {
        return ExternalChapterAPIsApiFp(this.configuration).getLastChapterByBookId(requestParameters.bookId, options).then((request) => request(this.axios, this.basePath));
    }
}

