/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CommentResponse
 */
export interface CommentResponse {
    /**
     * 
     * @type {string}
     * @memberof CommentResponse
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof CommentResponse
     */
    'bookId'?: string;
    /**
     * 
     * @type {string}
     * @memberof CommentResponse
     */
    'chapterId'?: string;
    /**
     * 
     * @type {string}
     * @memberof CommentResponse
     */
    'username'?: string;
    /**
     * 
     * @type {string}
     * @memberof CommentResponse
     */
    'content'?: string;
    /**
     * 
     * @type {string}
     * @memberof CommentResponse
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof CommentResponse
     */
    'updatedAt'?: string;
    /**
     * 
     * @type {Array<any>}
     * @memberof CommentResponse
     */
    'replies'?: Array<any>;
}

