/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { UserProfileChangeAvatarResponse } from './user-profile-change-avatar-response';

/**
 * 
 * @export
 * @interface ApiResponseUserProfileChangeAvatarResponse
 */
export interface ApiResponseUserProfileChangeAvatarResponse {
    /**
     * 
     * @type {number}
     * @memberof ApiResponseUserProfileChangeAvatarResponse
     */
    'code'?: number;
    /**
     * 
     * @type {UserProfileChangeAvatarResponse}
     * @memberof ApiResponseUserProfileChangeAvatarResponse
     */
    'result'?: UserProfileChangeAvatarResponse;
    /**
     * 
     * @type {string}
     * @memberof ApiResponseUserProfileChangeAvatarResponse
     */
    'message'?: string;
}

