/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { UserProfileCreationResponse } from './user-profile-creation-response';

/**
 * 
 * @export
 * @interface ApiResponseUserProfileCreationResponse
 */
export interface ApiResponseUserProfileCreationResponse {
    /**
     * 
     * @type {number}
     * @memberof ApiResponseUserProfileCreationResponse
     */
    'code'?: number;
    /**
     * 
     * @type {UserProfileCreationResponse}
     * @memberof ApiResponseUserProfileCreationResponse
     */
    'result'?: UserProfileCreationResponse;
    /**
     * 
     * @type {string}
     * @memberof ApiResponseUserProfileCreationResponse
     */
    'message'?: string;
}

