/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { UserReadingHistory } from './user-reading-history';

/**
 * 
 * @export
 * @interface ApiResponseListUserReadingHistory
 */
export interface ApiResponseListUserReadingHistory {
    /**
     * 
     * @type {number}
     * @memberof ApiResponseListUserReadingHistory
     */
    'code'?: number;
    /**
     * 
     * @type {Array<UserReadingHistory>}
     * @memberof ApiResponseListUserReadingHistory
     */
    'result'?: Array<UserReadingHistory>;
    /**
     * 
     * @type {string}
     * @memberof ApiResponseListUserReadingHistory
     */
    'message'?: string;
}

