/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UserProfileDeleteResponse
 */
export interface UserProfileDeleteResponse {
    /**
     * 
     * @type {string}
     * @memberof UserProfileDeleteResponse
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserProfileDeleteResponse
     */
    'userId'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserProfileDeleteResponse
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserProfileDeleteResponse
     */
    'avatarUrl'?: string;
}

