/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ApiResponseFavouriteCountResponse } from '../models';
/**
 * ExternalAPIForFavouriteServiceApi - axios parameter creator
 * @export
 */
export const ExternalAPIForFavouriteServiceApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Total number of times the story has been favorite
         * @param {string} bookId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCountByBookId: async (bookId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'bookId' is not null or undefined
            assertParamExists('getCountByBookId', 'bookId', bookId)
            const localVarPath = `/favourite/external/count/{bookId}`
                .replace(`{${"bookId"}}`, encodeURIComponent(String(bookId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ExternalAPIForFavouriteServiceApi - functional programming interface
 * @export
 */
export const ExternalAPIForFavouriteServiceApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ExternalAPIForFavouriteServiceApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Total number of times the story has been favorite
         * @param {string} bookId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCountByBookId(bookId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseFavouriteCountResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getCountByBookId(bookId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ExternalAPIForFavouriteServiceApi.getCountByBookId']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ExternalAPIForFavouriteServiceApi - factory interface
 * @export
 */
export const ExternalAPIForFavouriteServiceApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ExternalAPIForFavouriteServiceApiFp(configuration)
    return {
        /**
         * 
         * @summary Total number of times the story has been favorite
         * @param {ExternalAPIForFavouriteServiceApiGetCountByBookIdRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCountByBookId(requestParameters: ExternalAPIForFavouriteServiceApiGetCountByBookIdRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseFavouriteCountResponse> {
            return localVarFp.getCountByBookId(requestParameters.bookId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for getCountByBookId operation in ExternalAPIForFavouriteServiceApi.
 * @export
 * @interface ExternalAPIForFavouriteServiceApiGetCountByBookIdRequest
 */
export interface ExternalAPIForFavouriteServiceApiGetCountByBookIdRequest {
    /**
     * 
     * @type {string}
     * @memberof ExternalAPIForFavouriteServiceApiGetCountByBookId
     */
    readonly bookId: string
}

/**
 * ExternalAPIForFavouriteServiceApi - object-oriented interface
 * @export
 * @class ExternalAPIForFavouriteServiceApi
 * @extends {BaseAPI}
 */
export class ExternalAPIForFavouriteServiceApi extends BaseAPI {
    /**
     * 
     * @summary Total number of times the story has been favorite
     * @param {ExternalAPIForFavouriteServiceApiGetCountByBookIdRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ExternalAPIForFavouriteServiceApi
     */
    public getCountByBookId(requestParameters: ExternalAPIForFavouriteServiceApiGetCountByBookIdRequest, options?: RawAxiosRequestConfig) {
        return ExternalAPIForFavouriteServiceApiFp(this.configuration).getCountByBookId(requestParameters.bookId, options).then((request) => request(this.axios, this.basePath));
    }
}

