/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ApiResponseBookIndexResponse } from '../models';
// @ts-ignore
import type { BookIndexUpdateRequest } from '../models';
/**
 * BookIndexControllerApi - axios parameter creator
 * @export
 */
export const BookIndexControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {BookIndexUpdateRequest} bookIndexUpdateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateBook: async (bookIndexUpdateRequest: BookIndexUpdateRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'bookIndexUpdateRequest' is not null or undefined
            assertParamExists('updateBook', 'bookIndexUpdateRequest', bookIndexUpdateRequest)
            const localVarPath = `/search/indexing/update_book`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(bookIndexUpdateRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * BookIndexControllerApi - functional programming interface
 * @export
 */
export const BookIndexControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = BookIndexControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {BookIndexUpdateRequest} bookIndexUpdateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateBook(bookIndexUpdateRequest: BookIndexUpdateRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseBookIndexResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateBook(bookIndexUpdateRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BookIndexControllerApi.updateBook']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * BookIndexControllerApi - factory interface
 * @export
 */
export const BookIndexControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = BookIndexControllerApiFp(configuration)
    return {
        /**
         * 
         * @param {BookIndexControllerApiUpdateBookRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateBook(requestParameters: BookIndexControllerApiUpdateBookRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseBookIndexResponse> {
            return localVarFp.updateBook(requestParameters.bookIndexUpdateRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for updateBook operation in BookIndexControllerApi.
 * @export
 * @interface BookIndexControllerApiUpdateBookRequest
 */
export interface BookIndexControllerApiUpdateBookRequest {
    /**
     * 
     * @type {BookIndexUpdateRequest}
     * @memberof BookIndexControllerApiUpdateBook
     */
    readonly bookIndexUpdateRequest: BookIndexUpdateRequest
}

/**
 * BookIndexControllerApi - object-oriented interface
 * @export
 * @class BookIndexControllerApi
 * @extends {BaseAPI}
 */
export class BookIndexControllerApi extends BaseAPI {
    /**
     * 
     * @param {BookIndexControllerApiUpdateBookRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BookIndexControllerApi
     */
    public updateBook(requestParameters: BookIndexControllerApiUpdateBookRequest, options?: RawAxiosRequestConfig) {
        return BookIndexControllerApiFp(this.configuration).updateBook(requestParameters.bookIndexUpdateRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

