/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ApiResponseListCommentResponse } from '../models';
/**
 * InternalCommentControllerApi - axios parameter creator
 * @export
 */
export const InternalCommentControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} bookId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getByBookId: async (bookId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'bookId' is not null or undefined
            assertParamExists('getByBookId', 'bookId', bookId)
            const localVarPath = `/comment/internal/book/{bookId}`
                .replace(`{${"bookId"}}`, encodeURIComponent(String(bookId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} chapterId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getByChapterId: async (chapterId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'chapterId' is not null or undefined
            assertParamExists('getByChapterId', 'chapterId', chapterId)
            const localVarPath = `/comment/internal/chapter/{chapterId}`
                .replace(`{${"chapterId"}}`, encodeURIComponent(String(chapterId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} username 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getByUsername: async (username: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'username' is not null or undefined
            assertParamExists('getByUsername', 'username', username)
            const localVarPath = `/comment/internal/{username}`
                .replace(`{${"username"}}`, encodeURIComponent(String(username)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * InternalCommentControllerApi - functional programming interface
 * @export
 */
export const InternalCommentControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = InternalCommentControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} bookId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getByBookId(bookId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseListCommentResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getByBookId(bookId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['InternalCommentControllerApi.getByBookId']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} chapterId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getByChapterId(chapterId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseListCommentResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getByChapterId(chapterId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['InternalCommentControllerApi.getByChapterId']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} username 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getByUsername(username: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseListCommentResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getByUsername(username, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['InternalCommentControllerApi.getByUsername']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * InternalCommentControllerApi - factory interface
 * @export
 */
export const InternalCommentControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = InternalCommentControllerApiFp(configuration)
    return {
        /**
         * 
         * @param {InternalCommentControllerApiGetByBookIdRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getByBookId(requestParameters: InternalCommentControllerApiGetByBookIdRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseListCommentResponse> {
            return localVarFp.getByBookId(requestParameters.bookId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {InternalCommentControllerApiGetByChapterIdRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getByChapterId(requestParameters: InternalCommentControllerApiGetByChapterIdRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseListCommentResponse> {
            return localVarFp.getByChapterId(requestParameters.chapterId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {InternalCommentControllerApiGetByUsernameRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getByUsername(requestParameters: InternalCommentControllerApiGetByUsernameRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseListCommentResponse> {
            return localVarFp.getByUsername(requestParameters.username, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for getByBookId operation in InternalCommentControllerApi.
 * @export
 * @interface InternalCommentControllerApiGetByBookIdRequest
 */
export interface InternalCommentControllerApiGetByBookIdRequest {
    /**
     * 
     * @type {string}
     * @memberof InternalCommentControllerApiGetByBookId
     */
    readonly bookId: string
}

/**
 * Request parameters for getByChapterId operation in InternalCommentControllerApi.
 * @export
 * @interface InternalCommentControllerApiGetByChapterIdRequest
 */
export interface InternalCommentControllerApiGetByChapterIdRequest {
    /**
     * 
     * @type {string}
     * @memberof InternalCommentControllerApiGetByChapterId
     */
    readonly chapterId: string
}

/**
 * Request parameters for getByUsername operation in InternalCommentControllerApi.
 * @export
 * @interface InternalCommentControllerApiGetByUsernameRequest
 */
export interface InternalCommentControllerApiGetByUsernameRequest {
    /**
     * 
     * @type {string}
     * @memberof InternalCommentControllerApiGetByUsername
     */
    readonly username: string
}

/**
 * InternalCommentControllerApi - object-oriented interface
 * @export
 * @class InternalCommentControllerApi
 * @extends {BaseAPI}
 */
export class InternalCommentControllerApi extends BaseAPI {
    /**
     * 
     * @param {InternalCommentControllerApiGetByBookIdRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InternalCommentControllerApi
     */
    public getByBookId(requestParameters: InternalCommentControllerApiGetByBookIdRequest, options?: RawAxiosRequestConfig) {
        return InternalCommentControllerApiFp(this.configuration).getByBookId(requestParameters.bookId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {InternalCommentControllerApiGetByChapterIdRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InternalCommentControllerApi
     */
    public getByChapterId(requestParameters: InternalCommentControllerApiGetByChapterIdRequest, options?: RawAxiosRequestConfig) {
        return InternalCommentControllerApiFp(this.configuration).getByChapterId(requestParameters.chapterId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {InternalCommentControllerApiGetByUsernameRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InternalCommentControllerApi
     */
    public getByUsername(requestParameters: InternalCommentControllerApiGetByUsernameRequest, options?: RawAxiosRequestConfig) {
        return InternalCommentControllerApiFp(this.configuration).getByUsername(requestParameters.username, options).then((request) => request(this.axios, this.basePath));
    }
}

