/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ApiResponsePageRecordResponse } from '../models';
/**
 * HistoryRecordControllerApi - axios parameter creator
 * @export
 */
export const HistoryRecordControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} userId 
         * @param {number} [page] 
         * @param {number} [size] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getRecordByUserId: async (userId: string, page?: number, size?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('getRecordByUserId', 'userId', userId)
            const localVarPath = `/history/record/{userId}`
                .replace(`{${"userId"}}`, encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (size !== undefined) {
                localVarQueryParameter['size'] = size;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * HistoryRecordControllerApi - functional programming interface
 * @export
 */
export const HistoryRecordControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = HistoryRecordControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} userId 
         * @param {number} [page] 
         * @param {number} [size] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getRecordByUserId(userId: string, page?: number, size?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponsePageRecordResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getRecordByUserId(userId, page, size, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['HistoryRecordControllerApi.getRecordByUserId']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * HistoryRecordControllerApi - factory interface
 * @export
 */
export const HistoryRecordControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = HistoryRecordControllerApiFp(configuration)
    return {
        /**
         * 
         * @param {HistoryRecordControllerApiGetRecordByUserIdRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getRecordByUserId(requestParameters: HistoryRecordControllerApiGetRecordByUserIdRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponsePageRecordResponse> {
            return localVarFp.getRecordByUserId(requestParameters.userId, requestParameters.page, requestParameters.size, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for getRecordByUserId operation in HistoryRecordControllerApi.
 * @export
 * @interface HistoryRecordControllerApiGetRecordByUserIdRequest
 */
export interface HistoryRecordControllerApiGetRecordByUserIdRequest {
    /**
     * 
     * @type {string}
     * @memberof HistoryRecordControllerApiGetRecordByUserId
     */
    readonly userId: string

    /**
     * 
     * @type {number}
     * @memberof HistoryRecordControllerApiGetRecordByUserId
     */
    readonly page?: number

    /**
     * 
     * @type {number}
     * @memberof HistoryRecordControllerApiGetRecordByUserId
     */
    readonly size?: number
}

/**
 * HistoryRecordControllerApi - object-oriented interface
 * @export
 * @class HistoryRecordControllerApi
 * @extends {BaseAPI}
 */
export class HistoryRecordControllerApi extends BaseAPI {
    /**
     * 
     * @param {HistoryRecordControllerApiGetRecordByUserIdRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HistoryRecordControllerApi
     */
    public getRecordByUserId(requestParameters: HistoryRecordControllerApiGetRecordByUserIdRequest, options?: RawAxiosRequestConfig) {
        return HistoryRecordControllerApiFp(this.configuration).getRecordByUserId(requestParameters.userId, requestParameters.page, requestParameters.size, options).then((request) => request(this.axios, this.basePath));
    }
}

