/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ApiResponseRecordResponse } from '../models';
// @ts-ignore
import type { RecordRequest } from '../models';
/**
 * InternalHistoryRecordControllerApi - axios parameter creator
 * @export
 */
export const InternalHistoryRecordControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {RecordRequest} recordRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        saveRecord: async (recordRequest: RecordRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'recordRequest' is not null or undefined
            assertParamExists('saveRecord', 'recordRequest', recordRequest)
            const localVarPath = `/internal/save-record`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(recordRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * InternalHistoryRecordControllerApi - functional programming interface
 * @export
 */
export const InternalHistoryRecordControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = InternalHistoryRecordControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {RecordRequest} recordRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async saveRecord(recordRequest: RecordRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseRecordResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.saveRecord(recordRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['InternalHistoryRecordControllerApi.saveRecord']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * InternalHistoryRecordControllerApi - factory interface
 * @export
 */
export const InternalHistoryRecordControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = InternalHistoryRecordControllerApiFp(configuration)
    return {
        /**
         * 
         * @param {InternalHistoryRecordControllerApiSaveRecordRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        saveRecord(requestParameters: InternalHistoryRecordControllerApiSaveRecordRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseRecordResponse> {
            return localVarFp.saveRecord(requestParameters.recordRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for saveRecord operation in InternalHistoryRecordControllerApi.
 * @export
 * @interface InternalHistoryRecordControllerApiSaveRecordRequest
 */
export interface InternalHistoryRecordControllerApiSaveRecordRequest {
    /**
     * 
     * @type {RecordRequest}
     * @memberof InternalHistoryRecordControllerApiSaveRecord
     */
    readonly recordRequest: RecordRequest
}

/**
 * InternalHistoryRecordControllerApi - object-oriented interface
 * @export
 * @class InternalHistoryRecordControllerApi
 * @extends {BaseAPI}
 */
export class InternalHistoryRecordControllerApi extends BaseAPI {
    /**
     * 
     * @param {InternalHistoryRecordControllerApiSaveRecordRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InternalHistoryRecordControllerApi
     */
    public saveRecord(requestParameters: InternalHistoryRecordControllerApiSaveRecordRequest, options?: RawAxiosRequestConfig) {
        return InternalHistoryRecordControllerApiFp(this.configuration).saveRecord(requestParameters.recordRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

